import PDFDocument from 'pdfkit';

export function buildInvoicePdf({ invoiceNumber, customer, items, subtotal, discount, tax, total }) {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    doc.fontSize(22).text('BAKERY WHOLESALE INVOICE', { align: 'center' });
    doc.moveDown();
    doc.fontSize(11).text(`Invoice: ${invoiceNumber}`);
    doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`);
    doc.moveDown();
    doc.fontSize(13).text('Bill To');
    doc.fontSize(11).text(customer.name);
    if (customer.phone) doc.text(`Phone: ${customer.phone}`);
    if (customer.address) doc.text(customer.address);
    if (customer.gstin) doc.text(`GSTIN: ${customer.gstin}`);
    doc.moveDown();

    doc.fontSize(11).text('Product', 50, doc.y);
    doc.text('Qty', 300, doc.y);
    doc.text('Price', 370, doc.y);
    doc.text('Amount', 450, doc.y);
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.5);

    for (const item of items) {
      const y = doc.y;
      doc.text(item.product_name, 50, y, { width: 230 });
      doc.text(String(item.quantity), 300, y);
      doc.text(`Rs. ${Number(item.unit_price).toFixed(2)}`, 370, y);
      doc.text(`Rs. ${Number(item.amount).toFixed(2)}`, 450, y);
      doc.moveDown(0.7);
    }

    doc.moveDown();
    doc.text(`Subtotal: Rs. ${Number(subtotal).toFixed(2)}`, { align: 'right' });
    doc.text(`Discount: Rs. ${Number(discount).toFixed(2)}`, { align: 'right' });
    doc.text(`Tax: Rs. ${Number(tax).toFixed(2)}`, { align: 'right' });
    doc.fontSize(14).text(`TOTAL: Rs. ${Number(total).toFixed(2)}`, { align: 'right' });
    doc.moveDown(2);
    doc.fontSize(9).text('Generated by Cloud-Based Invoice Management System', { align: 'center' });
    doc.end();
  });
}
